services:
  - type: web
    name: fastapi-btc-ws
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn fastapi_btc_ws:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
